name: Deploy Grudge Codex Frontend to GitHub Pages

on:
  push:
    branches: ["main"]
  release:
    types: [created]
  workflow_dispatch:

# Sets permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping queued runs but not canceling in-progress runs
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 18.x
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'
          cache: 'npm'

      - name: install htmllint 
         run: npm i grunt-htmllint

      - name: Install dependencies
        run: npm ci

      - name: Run Grunt build
        run: npx grunt build

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'dist' # Upload only the dist/ folder with static assets

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
